### PR TITLE
Ft 180889302 submit button

### PR DESCRIPTION
**Pull request by ginabeki**
#### What does this PR do?
- Creates submit button with hover effect
#### Description of Task to be completed?
- Create submit button with hover effect
#### How should this be manually tested?
`npm install` and then open `index.html` on any browser of your choice.
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/180889302
#### Screenshots (if appropriate)

https://user-images.githubusercontent.com/59937419/151206298-4f3089c0-e1f6-4824-bf1d-51a771c64c62.mp4

#### Questions:
- None

### CODE REVIEW

**Comment by e-liyai** [comment]
@ginabeki  this looks fine, one edit request, can we line up the with and the textarea to match the width of the inputs above, so that we eliminate the trailing space.

**Review by e-liyai — CHANGES_REQUESTED** [review]
@ginabeki this looks fine, one edit request, can we line up the with and the textarea to match the width of the inputs above, so that we eliminate the trailing space.

**Comment by ginabeki** [comment]
> @ginabeki this looks fine, one edit request, can we line up the with and the textarea to match the width of the inputs above, so that we eliminate the trailing space.

@e-liyai on it.

**Comment by ginabeki** [comment]
> > @ginabeki this looks fine, one edit request, can we line up the with and the textarea to match the width of the inputs above, so that we eliminate the trailing space.
> 
> @e-liyai on it.


@e-liyai Done.

**Pull request merged**
