### PR TITLE
Ft 180889110 survey form

### PR DESCRIPTION
**Pull request by ginabeki**
#### What does this PR do?
- Creates input fields for the name, email, & phone number part of the survey form
#### Description of Task to be completed?
- Create input fields for the name, email, & phone number part of the survey form.
#### How should this be manually tested?
- `npm install` and then open the `index.html` file on the browser of your choice.
#### Any background context you want to provide?
- None
#### What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/180889110
- https://www.pivotaltracker.com/story/show/180889228

#### Screenshots (if appropriate)
Capture

#### Questions:
- None

### CODE REVIEW

**Review by e-liyai — CHANGES_REQUESTED** [review]
Hey @ginabeki, please provide screenshots for this.

**Comment by ginabeki** [comment]
> Hey @ginabeki, please provide screenshots for this.

Capture

**Comment by ginabeki** [comment]
> > Hey @ginabeki, please provide screenshots for this.
> 
> Capture

Hey @e-liyai I have attached the screenshot - above.

**Review by e-liyai — APPROVED** [review]
lg

**Review by puritybirir — APPROVED** [review]

**Pull request merged**
